### ISSUE TITLE
Deleting a deployment does not delete replicaset

### ISSUE THREAD

**Issue by rahulinux** [ansible/ansible-kubernetes-modules#18]
I'm trying to delete deployment using state = absent, but it does not delete replicaset. 

Deployment example: 

```
- name: Deploy {{ name }} 
  k8s_extensions_v1beta1_deployment:
    name: '{{ name }}' 
    namespace: '{{ namespace | default("default")}}'
    state: '{{ state }}' 
    #    dry_run: yes
    debug: yes
    spec_template_metadata_name: '{{ name }}' 
    labels:
      app: '{{ name }}' 
    spec_selector_match_labels:
      app: '{{ name }}' 
    spec_template_metadata_labels:
      app: '{{ name }}' 
    selector_match_labels:
      app: '{{ name }}' 
    selector_match_expressions:
     - { key: "app", operator: In, values: ["{{ name }}"]}
    containers:
      - name: '{{ name }}'
        image: '{{ image }}' 
        ports:
        - container_port: '{{ port }}' 
          protocol: TCP
          name: '{{ name }}' 
    replicas: 1
  register: create_deployment
```

**Comment by echupriyanov** [comment]
These modules use Openshift Python REST Client, which in turn calls DeleteObject with empty V1DeleteOptions unconditionally.
As result, Deployment is deleted with `orphan` propagation policy.
Not sure how to fix this properly. I've cloned https://github.com/openshift/openshift-restclient-python to https://github.com/echupriyanov/openshift-restclient-python

**Comment by fabianvf** [comment]
This is correct. We've actually included this change in the main openshift-restclient-python for a quick fix [1], we're not sure yet what the best way to handle this correctly would look like. It should be fixed with the latest openshift-restclient-python though. 

1. https://github.com/openshift/openshift-restclient-python/commit/31581bdc9cad334a31e921f52ae72ee53b7db831#diff-93163b9d3a7911b26d817c4c84079df1
